[project]
name = 'aegis'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.agent-evaluator-oracle]
path = 'contracts/agent-evaluator-oracle.clar'
clarity_version = 4
epoch = 'latest'

[contracts.agent-registry]
path = 'contracts/agent-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.quest-escrow]
path = 'contracts/quest-escrow.clar'
clarity_version = 4
epoch = 'latest'

[contracts.subscription-manager]
path = 'contracts/subscription-manager.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
